# Generated by Django 5.2.4 on 2025-07-09 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='id',
        ),
        migrations.AddField(
            model_name='expense',
            name='expenseId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
