# Generated by Django 5.2.4 on 2025-11-12 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_income'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Income',
        ),
    ]
